# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 1.0

joint1: #AX-12
  ID: 1
  Return_Delay_Time: 0
  #Operating_Mode: 3
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  #Moving_Speed: 1023

joint2: #AX-12
  ID: 2
  Return_Delay_Time: 0
  #Operating_Mode: 3
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  #Moving_Speed: 1023
