# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 1.0

joint2:  #RX-64
  ID: 2
  Return_Delay_Time: 0
  #Operating_Mode: 3
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  #Moving_Speed: 1023

#joint3:  #RX-64
#  ID: 3
#  Return_Delay_Time: 0
#  #Operating_Mode: 3
#  CW_Angle_Limit: 0
#  CCW_Angle_Limit: 1023
#  #Moving_Speed: 1023

#joint4:  #RX-64
#  ID: 4
#  Return_Delay_Time: 0
#  #Operating_Mode: 3
#  CW_Angle_Limit: 0
#  CCW_Angle_Limit: 1023
#  #Moving_Speed: 1023

#joint5:  #EX-106
#  ID: 5
#  Return_Delay_Time: 0
#  #Operating_Mode: 3
#  CW_Angle_Limit: 0
#  CCW_Angle_Limit: 4095
#  #Moving_Speed: 1023

#joint6:  #EX-106
#  ID: 6
#  Return_Delay_Time: 0
#  #Operating_Mode: 3
#  CW_Angle_Limit: 0
#  CCW_Angle_Limit: 4095
#  #Moving_Speed: 1023

#joint7:  #MX-106
#  ID: 7
#  Return_Delay_Time: 250
#  #Operating_Mode: 3
#  CW_Angle_Limit: 0
#  CCW_Angle_Limit: 4095
#  #Moving_Speed: 1023

