joint:
  names: [joint2, joint3, joint4, joint5, joint6, joint7]
motion:
  names: [right, zero, left]
  right:
    step: [-3.14, -3.14, -3.14, -3.14, -3.14, -3.14]  # radian
    time_from_start: 2.0  # sec
  zero:
    step: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start: 3.0
  left:
    step: [3.14, 3.14, 3.14, 3.14, 3.14, 3.14,]
    time_from_start: 6.0

